### ISSUE TITLE
インポート中、画面をリロードしてしまうと処理が再開できない

### ISSUE THREAD

**Issue by moriaiy** [MacareuxDigital/csv_user_import_export#24]
インポート処理中、管理メニューからImport User CSVにアクセスし直すと、
"A queue already exists! Would you like to delete it?" という確認ポップアップが表示されます。
ここで「キャンセル」を選んだとき、処理が再開できると思ったのですが、「キャンセル」を選んでも何も起こりませんでした。

また、画面をF5キーでリロードした場合は何もポップアップが表示されません。
（そのまま、ヘッダーの取り込み設定を再度行って「インポート」ボタンをクリックすると、処理が再開されるようです）

詳しくは、添付の動画をご覧ください。
https://user-images.githubusercontent.com/50855696/121146071-88b41280-c87a-11eb-84d8-545afba9ce8b.mp4

**Comment by hissy** [comment]
@biplobice 

Can you understand what she said and tell Aye how to fix it?

**Comment by biplobice** [comment]
@Hmone23 
1. Please show the popup  `A queue already exists! Would you like to delete it?` on page refresh as well.

@hissy 
2. I'm thinking to change the popup as follows-

**A queue already exists. Would you like to continue?**

- Option A: `Continue` will continue the existing queue
- Option B: `Clear` will clear the existing queue

What do you think?

@Hmone23 If @hissy agree, please implement this also.

**Comment by hissy** [comment]
@biplobice 

Yeah, it would be nice
