### ISSUE TITLE
Can't export user from version 8.2.0b1. Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by biplobice** [MacareuxDigital/csv_user_import_export#3]
`Whoops \ Exception \ ErrorException (E_RECOVERABLE_ERROR)
Object of class DateTime could not be converted to string`

![screen shot 2017-06-02 at 10 30 40 am](https://cloud.githubusercontent.com/assets/2462951/26707419/bc7bfa40-477f-11e7-8b09-f3513b4d94da.png)

**Comment by hissy** [comment]
I believe this issue has been fixed via #4
